version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.javalin:javalin
    versions:
    - 3.13.3
    - 3.13.4
    - 3.13.5
  - dependency-name: org.jetbrains.kotlin.jvm
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: io.github.microutils:kotlin-logging
    versions:
    - 2.0.4
  - dependency-name: io.reactivex.rxjava2:rxjava
    versions:
    - 2.2.20
  - dependency-name: com.squareup.okhttp3:okhttp
    versions:
    - 4.9.0
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.0
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.0
